### ISSUE TITLE
Morning session: peer-to-peer code reviews - Module 2- week 4 - Friday

### ISSUE THREAD

**Issue by Diegogagan2587** [ClaudiaRojasSoto/Leaderboard#5]
# Code Review implemented during the Morning Session
code review implemented by @Dachrono @Diegogagan2587 and @Zven94 to @ClaudiaRojasSoto 
## Suggested Changes

 ![congrats](https://camo.githubusercontent.com/9fd793d5bc552a5d52d9a82858745665fd0d73c7fa880dec3d41cf5d9f065f83/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f447a6c6a327a72396b356b5a5167387766632f67697068792e676966) [ ![congrats]
You have done a great job so far, however, there are some opportunities to improve your project:

- We notice your background is not showing, to resolve this you need to 
   - Import the image without your index.js as you do with a module 
   - Assing the path that leads to the image to a variable
   - call the HTML IMG element that will contain the images
   - assist the source property to this element, so in that way, Webpack will include
   
- Do not import the index.js from the index.html template since Webpack will do it for you.

**Comment by ClaudiaRojasSoto** [comment]
Thank you, guys! all your suggestions were fixed.

[You can check clicking here](https://claudiarojassoto.github.io/Leaderboard/dist/)



@Diegogagan2587 
@Zven94 
@Dachrono
